FROM ubuntu:22.04

RUN apt update && apt install python3 curl -y
RUN curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp

RUN chmod a+rx /usr/local/bin/yt-dlp

ENTRYPOINT ["/usr/local/bin/yt-dlp"]

# define start condition
CMD ["https://www.youtube.com/watch?v=XsqlHHTGQrw"]